[package]
name = "staticvec"
description = "Implements a fixed-capacity Vec alternative backed by a static array using const generics."
homepage = "https://bitbucket.org/SlightlyOutOfPhase/staticvec"
repository = "https://bitbucket.org/SlightlyOutOfPhase/staticvec"
license = "MIT"
readme = "README.md"
version = "0.1.8"
authors = ["SlightlyOutOfPhase <slightlyoutofphase@gmail.com>"]
keywords = ["vec","array","container","vector","stack"]
categories = ["data-structures"]
edition = "2018"

[profile.dev]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 16
panic = 'unwind'
incremental = false
overflow-checks = true

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = false

[[bin]]
name = "demo"
path = "demo/demo.rs"
doc = false

[dependencies]
